# Generated by Django 3.2 on 2022-03-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220309_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='balance',
        ),
    ]
