# Generated by Django 3.2 on 2022-03-04 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220302_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='inception',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
