# Generated by Django 3.2 on 2022-03-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220309_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinfo',
            name='owner',
        ),
    ]
