# Generated by Django 3.2 on 2022-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fund_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
